###
GET http://localhost:1234/gettables
###
GET http://localhost:1234/api/
###
POST http://localhost:1234/api/publish
Content-Type: application/json

{
    "appName":"Youtube",
    "appVendor":"google inc",
    "appCategory":"Entertainment"
}
###
PUT http://localhost:1234/api/download/Subway surfers
###
PUT http://localhost:1234/api/download/Netflix
###
GET http://localhost:1234/api/Youtube
###
GET http://localhost:1234/api/published/google
###
GET http://localhost:1234/api/type/Financial services
###
GET http://localhost:1234/api/users/1
###
PUT http://localhost:1234/api/rank/Youtube/5
###
GET http://localhost:1234/api/bytyperate/Financial services/4
###
DELETE http://localhost:1234/api/delbyid/13008
###
DELETE http://localhost:1234/api/delbyname/Amazon
###
DELETE http://localhost:1234/api/delbyrate/10
###